add all files
stepancar-web-programming/2022-fall-lab-portfolio-molikov-ilya-andreevich pull request #2
Opened 2022-11-30 14:47 UTC by moliksey

2022-12-03 05:25 UTC, stepancar commented on README.md
> +Я сам не решился делать свое портфолио потому что туда особо нечего добавить, да и в целом хотелось сделать что-то связанное с эти игроком, потому что он лучший(по моему скромному мнению). Ну и еще т
👍

2022-12-03 05:26 UTC, stepancar commented on package.json
> +    "react-scripts": "5.0.1",
Не забывайте про разницу dependencies/devDependencies. вопрос из рубежки

2022-12-03 05:27 UTC, stepancar commented on src/App.test.js
> +    const linkElement = screen.getByText(/learn react/i);
Тест ведь не проходит, верно?

2022-12-03 05:43 UTC, stepancar commented on src/State.js
> +export const subscriber = (observer) => {
Если правильно понял идею, то вы хотите обновлять состояние при изменении каунтера. Для этого вы использовали ReactDom.render. Это оригинальное решение, такое редко встретишь на просторе интернета. Это говорит мне о том, что над лабой проводилась работа, шел собственный мыслительный процесс. За это спасибо.

Однако, такое решение не очень хорошее. Дело в том, что в таком случае происходит много лишней работы со стороны реакта.

Вам нужно использовать useState для обновления состояния

2022-12-03 05:55 UTC, stepancar commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
Пожалуйста, замените на свою

2022-12-06 16:08 UTC, moliksey commented on src/State.js
> +export const subscriber = (observer) => {
Исправлено

2022-12-06 16:09 UTC, moliksey commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
Я даже не обратил внимание на то что там лого реакта. Исправил, спасибо

2022-12-06 16:10 UTC, moliksey commented on src/App.test.js
> +    const linkElement = screen.getByText(/learn react/i);
Это тест автоматически сформированный реактом, я его удалил

2022-12-06 16:12 UTC, moliksey commented on package.json
> +    "react-scripts": "5.0.1",
Нужно удалить devDependencies?

2022-12-06 16:16 UTC, moliksey commented on package.json
> +    "react-scripts": "5.0.1",
Верней даже так, нужно какие-то зависимости перенести в devDependencies?

2022-12-17 03:17 UTC, stepancar commented on package.json
> +    "react-scripts": "5.0.1",
Верно. Часть зависимостей тут являются dev зависимостями

2022-12-17 03:18 UTC, stepancar commented on src/PlayingHistory/Tournaments/Tournaments.jsx
> +    let rowsTournaments = props.tournaments.map(el => <tr>
пожалуйста, проверьте код с помощью eslint перед отправкой на ревью

2022-12-17 03:19 UTC, stepancar requested changes
Пожалуйста, убедитесь, что код котов к ревью, перед созданием ПР

2022-12-28 05:43 UTC, stepancar commented on src/MainPage/Post/Post.jsx
> +          <Button variant="secondary" onClick={like}>Like!</Button>
обратите внимание что like - новая ссылка на каждом рендере. в таких случаях вам пригодится useCallback

2022-12-28 05:45 UTC, stepancar commented on package.json
> +    "react-scripts": "5.0.1",
@moliksey , так и не увидел резолвинга этого issue

2022-12-28 19:48 UTC, stepancar approved these changes
@moliksey не забудьте смержить ПР

2023-01-24 15:04 UTC, merged